// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCluQ-sPR26iMcpygpzU9PIOAQv8bGTkUw',
    appId: '1:706122145272:web:ae3bc3dd880803a1df8a0d',
    messagingSenderId: '706122145272',
    projectId: 'newsapp-3dce8',
    authDomain: 'newsapp-3dce8.firebaseapp.com',
    storageBucket: 'newsapp-3dce8.appspot.com',
    measurementId: 'G-KS2E6232YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBaZ3Z502fQuOYk5RafIDTPaLi-wGSrQ',
    appId: '1:706122145272:android:324d268e61b7322edf8a0d',
    messagingSenderId: '706122145272',
    projectId: 'newsapp-3dce8',
    storageBucket: 'newsapp-3dce8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCluQ-sPR26iMcpygpzU9PIOAQv8bGTkUw',
    appId: '1:706122145272:web:7282fd4c2c598db2df8a0d',
    messagingSenderId: '706122145272',
    projectId: 'newsapp-3dce8',
    authDomain: 'newsapp-3dce8.firebaseapp.com',
    storageBucket: 'newsapp-3dce8.appspot.com',
    measurementId: 'G-R9F0RWTW7Q',
  );
}
